name: ImmortalWrt Image Builder (OpenWrt 24)
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  PROFILE: generic
  UCI_CUSTOM_FILE: uci-custom
  PACKAGES_LIST_FILE: packages.list
  PACKAGES_FOLDER: packages
  UPLOAD_BIN_DIR: true
  UPLOAD_FIRMWARE: true
  UPLOAD_COWTRANSFER: false
  UPLOAD_WETRANSFER: false  
  UPLOAD_RELEASE: true
  # ROOTFS_PARTSIZE: 512   # Reconfigure the rootfs partition size (for x86 build only), variable set in MB
  DOWNLOAD_URL: https://downloads.immortalwrt.org/releases/24.10.2/targets/x86/64/immortalwrt-imagebuilder-24.10.2-x86-64.Linux-x86_64.tar.zst
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev libncursesw5-dev zlib1g-dev gawk git gettext libssl-dev xsltproc wget unzip python3 qemu-utils genisoimage zstd

    - name: Download and extract Image Builder
      run: |
        wget -O /tmp/imagebuilder.tar.zst $DOWNLOAD_URL
        sudo tar -I zstd -C /tmp -xvf /tmp/imagebuilder.tar.zst

    - name: Set Image Builder root directory
      run: |
        ROOT_DIRECTORY=$(basename $DOWNLOAD_URL .tar.zst)
        echo "ROOT_DIRECTORY=/tmp/$ROOT_DIRECTORY" >> $GITHUB_ENV

    - name: Modify .config file
      run: |
        CONFIG_FILE="$ROOT_DIRECTORY/.config"
        # Disable iso and virtual disk image generation for x86
        sudo sed -i 's/^CONFIG_ISO_IMAGES=y/# CONFIG_ISO_IMAGES is not set/' $CONFIG_FILE
        sudo sed -i 's/^CONFIG_USES_EXT4=y/# CONFIG_USES_EXT4 is not set/' $CONFIG_FILE
        sudo sed -i 's/^CONFIG_TARGET_ROOTFS_EXT4FS=y/# CONFIG_TARGET_ROOTFS_EXT4FS is not set/' $CONFIG_FILE
        sudo sed -i 's/^CONFIG_GRUB_IMAGES=y/# CONFIG_GRUB_IMAGES is not set/' $CONFIG_FILE
        # sudo sed -i 's/^CONFIG_QCOW2_IMAGES=y/# CONFIG_QCOW2_IMAGES is not set/' $CONFIG_FILE
        sudo sed -i 's/^CONFIG_VDI_IMAGES=y/# CONFIG_VDI_IMAGES is not set/' $CONFIG_FILE
        # sudo sed -i 's/^CONFIG_VMDK_IMAGES=y/# CONFIG_VMDK_IMAGES is not set/' $CONFIG_FILE
        sudo sed -i 's/^CONFIG_VHDX_IMAGES=y/# CONFIG_VHDX_IMAGES is not set/' $CONFIG_FILE
        # Reconfigure the rootfs partition size (for x86 build only)
        if [ -n "${{ env.ROOTFS_PARTSIZE }}" ] && [ "${{ env.PROFILE }}" = "generic" ]; then
          sudo sed -i 's/CONFIG_TARGET_ROOTFS_PARTSIZE=.*/CONFIG_TARGET_ROOTFS_PARTSIZE=${{ env.ROOTFS_PARTSIZE }}/g' $CONFIG_FILE
        fi

    - name: Copy files
      run: |
        # Creator folders
        sudo mkdir -p $ROOT_DIRECTORY/files/etc/uci-defaults
        sudo mkdir -p $ROOT_DIRECTORY/packages
        # Copy custom setting file
        sudo cp $UCI_CUSTOM_FILE $ROOT_DIRECTORY/files/etc/uci-defaults
        # Copy packages list
        sudo cp $PACKAGES_LIST_FILE $ROOT_DIRECTORY/files/packages.list
        # Copy ipk files
        sudo cp $PACKAGES_FOLDER/*.ipk $ROOT_DIRECTORY/packages

    - name: Compile firmware
      run: |
        sudo sh prepare-packages.sh
        cd $ROOT_DIRECTORY
        PACKAGES=$(cat $ROOT_DIRECTORY/files/packages.list | tr '\n' ' ')
        sudo make image PROFILE="$PROFILE" PACKAGES="$PACKAGES" FILES="files" ROOTFS_PARTSIZE="800"
        echo "FILE_DATE=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
        # Organize files
        sudo mkdir -p /tmp/bin_firmware
        sudo find bin -type f -exec sudo cp {} /tmp/bin_firmware/ \;
        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
        echo "FILE_TIME=$(date "+%Y年%m月%d日-%H点")" >> $GITHUB_ENV
        echo "TAG_TIME=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: Upload firmware
      uses: actions/upload-artifact@main
      with:
        name: ImmortalWrt-firmware-${{ env.PROFILE }}-${{ env.FILE_DATE }}
        path: /tmp/bin_firmware

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 2

    - name: Generate release tag
      id: tag
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      run: |
        echo "release_tag=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_OUTPUT
        touch release.txt
        [ $UPLOAD_COWTRANSFER = true ] && echo "🔗 [Cowtransfer](${{ steps.cowtransfer.outputs.url }})" >> release.txt
        [ $UPLOAD_WETRANSFER = true ] && echo "🔗 [WeTransfer](${{ steps.wetransfer.outputs.url }})" >> release.txt
        echo "status=success" >> $GITHUB_OUTPUT

    - name: 发布至release
      id: release
      uses: ncipollo/release-action@v1.21.0
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      with:
        name: ${{ env.FILE_TIME }}  「 ImmortalWrt_24.10-X86-64 」
        allowUpdates: true
        tag: ${{ env.TAG_TIME }}
        commit: main
        token: ${{ secrets.REPO_TOKEN }}
        body: |
          功能介绍：该版本luci为24.10，内核版本6.12，目前包含Passwall、Mosdns、Docker、iStore商店等基础插件，其他插件可以用iStore商店安装，满足普通用户使用了。
          [固件源码](https://github.com/immortalwrt/immortalwrt)
          由衷感谢所有为openwrt无私奉献的大佬们
          📥 固件下载
        artifacts: /tmp/bin_firmware/*
